### ISSUE TITLE
Longitude out of range gives latitude error

### ISSUE THREAD

**Issue by jwellman80** [ASCOMInitiative/ASCOM.Alpaca.Simulators#10]
When entering an out of range value for the Longitude minutes you receive an error that the Latitude Minutes are out of bounds. 

![image](https://user-images.githubusercontent.com/5726367/233139904-df45f7a2-0ba5-47ed-8a9b-ef1ff1d0d49b.png)

**Comment by DanielVanNoord** [comment]
Thanks, should be fixed in main now with [5e2008d](https://github.com/ASCOMInitiative/ASCOM.Alpaca.Simulators/commit/5e2008dd5b502cddfb17310689d6f0dbb6694cb6).
