### ISSUE TITLE
Add purely command-line mode

### ISSUE THREAD

**Issue by RReverser** [ASCOMInitiative/ASCOM.Alpaca.Simulators#20]
I want to use simulators in automated client library testing, just like ConformU can be used for testing server implementations.

Spawning simulators as a child process is not hard, but 2 things are currently missing for better control:

1. I'd like to be able to prevent spawning a browser tab with the GUI - when starting simulators, I don't want browser to start, let alone for those GUI tabs to linger after process is closed as it happens right now.
2. I'd like to be able to override the settings XML - as far as I can tell, it's currently hardcoded to a system-wide config path.

**Comment by DanielVanNoord** [comment]
1. You can turn off the browser start by changing Driver Setup -> Server Settings -> Uncheck Open Browser on Start and save
2. Currently you can get the XML profile through the simulator api, I will look at adding an option to provide one as well.

Are you trying to run more then one copy of the OmniSim at a time or just one that you can configure? Currently the settings are a bit hodgepodge as they are directly derived from the original platform simulators. I'm planning a major overhaul to make them more consistent for the next major release, so some of the smaller improvements may have to wait for that.

**Comment by RReverser** [comment]
> 1. You can turn off the browser start by changing Driver Setup -> Server Settings -> Uncheck Open Browser on Start and save

Yeah if I could provide my own XML that would be fine, so maybe it's just 1 issue rather than 2.

> Are you trying to run more then one copy of the OmniSim at a time or just one that you can configure?

Just one that I can configure and run in background.

**Comment by RReverser** [comment]
FWIW I don't think I need any per-device configuration yet anyway, all I want is ability to tweak listen address+port, debug/tracing logs and that browser launch option.

Basically, general server options instead of per device ones.

**Comment by DanielVanNoord** [comment]
I just added a --set-no-browser command. IP / Port settings are already available from the CLI.

**Comment by RReverser** [comment]
Thanks! This should do it for now.

**Comment by RReverser** [comment]
> * You can turn off the browser start by changing Driver Setup -> Server Settings -> Uncheck Open Browser on Start and save

Btw this checkbox doesn't seem to do anything. It's already unchecked for me, yet browser keeps opening.

**Comment by RReverser** [comment]
Looks like there are 2 places in this file that launch the browser without checking the setting name: https://github.com/ASCOMInitiative/ASCOM.Alpaca.Simulators/blob/378acd5bf09d9ec30e1933288f69caa29eef11b9/ASCOM.Alpaca.Simulators/Program.cs#L94

There is 1 more place in Startup.cs that calls the same method but does check the setting name , but I'm not sure what's the difference is between all those 3 calls and why some of them ignore the configuration.

**Comment by DanielVanNoord** [comment]
What operating system are you using? I'll retest a matching OS to make sure that there isn't a new bug.
If the OmniSim is already running in the background calling the program again will launch the browser attached to the existing session, regardless of the auto-start browser setting. This is to allow GUI users to recover the browser UI without needing the IP and Port. That's the two calls in Program.cs. Startup.cs is the actual auto start browser, it waits until all the background server parts are online before firing.

**Comment by RReverser** [comment]
> What operating system are you using?

Windows (11, if that matters).

Thanks for the explanation, I'll try and recheck that I'm not leaving zombie processes between reruns - maybe it's indeed still running in the background.

Is `--set-no-browser` going to override this behavios regardless of whether the app is already up and running?

**Comment by RReverser** [comment]
Yeah looks like that's the problem - for some reason, the `ascom.alpaca.simulators.exe` remains running in background even after my test runner's `.exe` has exited, so on the first run the behaviour is as expected but on the next one it's spawning a browser window.

That's weird, AFAIK child processes should be killed automatically when the parent dies, but apparently not in this case. I'll try to dig into why...

**Comment by RReverser** [comment]
Made a small workaround for now - manually killing the child process before mine exits - but that's probably not a great solution as it doesn't provide a graceful shutdown. I'll look into a better way later.

**Comment by RReverser** [comment]
Hm no, it still remains in the background afterwards... Ugh.

**Comment by RReverser** [comment]
> I just added a --set-no-browser command. IP / Port settings are already available from the CLI.

@DanielVanNoord It looks like this just configures simulators and exits immediately? Could it instead launch a normal instance of simulators, just configured not to launch browsers?
