### ISSUE TITLE
ASCOM Camera.Simulator Image Array

### ISSUE THREAD

**Issue by michealroberts** [ASCOMInitiative/ASCOM.Alpaca.Simulators#4]
I read here: https://ascom-standards.org/api/#/Camera%20Specific%20Methods/get_camera__device_number__imagearray

That the imagearray endpoint is in ...

_"... "column-major" order (column changes most rapidly) from the image's row and column perspective, while, from the array's perspective, serialisation is actually effected in "row-major" order (rightmost index changes most rapidly). This unintuitive outcome arises because the ASCOM Camera Interface specification defines the image column dimension as the rightmost array dimension."_

So, I just wanted to ask - the exposure array that is sent back, for the simulation where the camera X size is 800, and the camera y size is 600 ... what should the length of the first nested array be?

e.g.,:

```
[
   [ ... ] // <--- Should this be 600 elements long, or 800 elements?
]
```

Currently, I see that first nested array to be 600 elements, signifying that it is the first column of the CCD, and thus the array is ordered columns first.

I guess that makes sense physically if values are binned in the Y column.

Have I understood this correctly?

**Comment by DanielVanNoord** [comment]
I believe that you are correct. The OmniSim passes the camera tests and the de-serialized image matches the input. If you questions related to the Alpaca specification I would recommend asking them on the Developer Forum. You should be able to get more help there.
