### ISSUE TITLE
Relative focuser issue

### ISSUE THREAD

**Issue by Peter-Simpson** [ASCOMInitiative/ASCOM.Alpaca.Simulators#6]
Hi Daniel,

I've just found and fixed an issue in the Platform Focuser Simulator that also appears in the Alpaca simulator. The [Focuser Interface](https://ascom-standards.org/Help/Developer/html/P_ASCOM_DeviceInterface_IFocuserV3_Position.htm) specification requires the Focuser.Position property to return a PropertyNotImplementedException when the focuser is in RELATIVE mode. This wasn't happening in the Platform simulator and likewise is also not happening in the Omni-Simulator.

Best wishes, Peter

**Comment by DanielVanNoord** [comment]
Thanks, I fixed it in the OmniSim as well.
