### ISSUE TITLE
Bayer options return only 1/4 of the image

### ISSUE THREAD

**Issue by RReverser** [ASCOMInitiative/ASCOM.Alpaca.Simulators#9]
I've been testing my client against various options in camera simulator and noticed that, while monochrome & colour sensors return the full test image as expected, the Bayer option seems to only return 1/4 of the image.

I'm guessing there is some mixup due to RGGB being technically 4 values, but they should still result in the same dimensions of the raw image as the coloured one through interpolation.

I wasn't sure if it's a bug in my decoding, so I re-verified with CCDCiel and it shows the same:

Sensor Type == Monochrome:

![image](https://user-images.githubusercontent.com/557590/227788727-62d4ef28-d6cb-4425-98d9-5ee06a027a0e.png)

Sensor Type == Color:

![image](https://user-images.githubusercontent.com/557590/227788789-50897471-254b-45a7-9023-d6f27d8f491a.png)

Sensor Type == RGGB:

![image](https://user-images.githubusercontent.com/557590/227788628-94e14735-f3bd-4fdc-80ee-92529aec63de.png)

(same but debayered)

![image](https://user-images.githubusercontent.com/557590/227788963-b408963b-721f-42eb-8367-f6da0961d190.png)

For what it's worth, I don't know if those simulators are based on the same codebase, but I noticed that ASCOM Camera V2 Simulator exhibits the same issue.

**Comment by DanielVanNoord** [comment]
I've looked into this and I believe that it is behaving correct as the simulator does not scale the image. The CameraXSize and CameraYSize return the raw number of pixels (unbinned / unbayered) in the image array. When you put the simulator in Bayer mode it does not increase the size of the simulated image array so you get the same size with 4 Bayer pixels per pixel thus 1/4 of the b/w image. If you switch to Bayer mode and increase the image size to 1600 x 1200 you should get the whole image.

**Comment by RReverser** [comment]
> The CameraXSize and CameraYSize return the raw number of pixels (unbinned / unbayered) in the image array.

Right, I think what I'd expect from simulator is to update those sizes on mode change - same as what happens in real cameras that have multiple modes like DSLRs.

**Comment by Mauro-Sturaro** [comment]
I believe that the correct behavior is not to change the number of configured pixels, but to return each pixel of the original image to a single pixel of the Bayer matrix, thus obtaining the same field and the same resolution, as occurs in real sensors.
Now instead it take a pixel of the original image and map it, on 4 pixels of the returned image, each appropriately filtered, reducing the actual field of view.

**Comment by DanielVanNoord** [comment]
The ASCOM definition of resolution is the raw size of the array that is transmitted to the program. Are you asking for the same image just scaled down to quarter scale so it looks the same? A 800x600 array of LRGB bayer groups has the same CameraXSize and CameraYSize as a 800x600 monochrome sensor in ASCOM, but after processing will functionally be a 200x150 color image. Put another way an ASCOM Pixel is a single output point on a sensor.

The next major version is likely going to remove the "real" image replace it with defined test patterns.

**Comment by Mauro-Sturaro** [comment]
An 800x600 array from a monochrome camera has a CameraXSize and CameraYSize of 800x600. Similarly, an 800x600 array from an RGGB camera has the same CameraXSize and CameraYSize: 800x600. In both cases, images acquired—let's say with N.I.N.A.—are 800x600, and both images have the same field of view (FOV). It's only after processing that the image becomes a color image, and the final size depends on the algorithm chosen. If "simple averaging" is used, the final resolution of the image is 400x300 (one color pixel for each group of four RGGB pixels). However, if you choose a better algorithm like "Bilinear Interpolation" or "VNG," you obtain a color image with the same resolution as the sensor: 800x600.

I don't have an LRGB sensor, but I'm sure the same concepts apply to it as well: the raw resolution reported by the acquisition program is always 800x600 pixels.

Regardless, the FOV, which captures the entire M42 in this example, depends only on the focal length and sensor size (number_of_pixels * pixel_size), and never on the CFA matrix that is applied to the sensor pixels.
